### ISSUE TITLE
Create basic layout for payment form 

### ISSUE THREAD

**Issue by shemerey** [shemerey/ppfc#3]
Create basic layout and add following 

- [ ] normalize.css
- [ ] base.css (import following parts)
  - [ ] colors.css
  - [ ] typo.css

add basic layout colors, background color and position  form in the center of the page

**Comment by IlyaRucavitcyn** [comment]
You can find my PR for that issue [here](https://github.com/shemerey/ppfc/pull/4). Please have a look and if all is ok I wil rebase all the commits and then we can merge the branch into master!

**Comment by shemerey** [comment]
LGTM
